async function jsonReq(url,data){ const res = await fetch(url,{method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(data), credentials:'include'}); return res.json(); }
export async function getProdutos(){ const r = await fetch('/api/produtos_read.php', {credentials:'include'}); return r.json(); }
export async function createProduto(data){ return jsonReq('/api/produtos_create.php', data); }
export async function updateProduto(data){ return jsonReq('/api/produtos_update.php', data); }
export async function deleteProduto(id){ return jsonReq('/api/produtos_delete.php', {id_produto:id}); }
window.showAddItem = function(){ document.getElementById('addItemForm').style.display='block'; }
window.addItem = async function(){ const nome=document.getElementById('itemName').value; const sku=document.getElementById('itemSKU')?document.getElementById('itemSKU').value:''; const unidade=document.getElementById('itemUnidade')?parseInt(document.getElementById('itemUnidade').value):0; const qty=parseFloat(document.getElementById('itemQuantity').value||0); const resp = await createProduto({sku,nome,id_unidade:unidade,descricao:''}); if(resp.success){ alert('Produto criado'); location.reload(); } else alert('Erro: '+(resp.error||JSON.stringify(resp))); }
window.loadProdutos = async function(){ const r = await getProdutos(); const t = document.getElementById('itemsList'); if(!t) return; t.innerHTML=''; r.produtos.forEach(p=>{ const tr=document.createElement('tr'); tr.innerHTML=`<td>${p.id_produto}</td><td>${p.sku}</td><td>${p.nome}</td><td>${p.unidade_sigla}</td><td><button class='btn btn-sm btn-warning' onclick="(async ()=>{ const n=prompt('Nome', p.nome); if(!n) return; await updateProduto({id_produto:p.id_produto,nome:n}); location.reload(); })()">Editar</button> <button class='btn btn-sm btn-danger' onclick="(async ()=>{ if(!confirm('Deletar?')) return; await deleteProduto(${p.id_produto}); location.reload(); })()">Apagar</button></td>`; t.appendChild(tr); }); }
window.addEventListener('DOMContentLoaded', window.loadProdutos);
